### ISSUE TITLE
how determine the error status code

### ISSUE THREAD

**Issue by dohomi** [ilyalesik/react-fetch-hook#21]
Hi
I have a question about the error message. Currently I receive a `string` but it would be nice to show different message based on the response status - like 401 or 500.
Is there a way to do this? 
Thanks!

**Comment by ilyalesik** [comment]
Hi, @dohomi! Thank you for the issue.

I has implemented it at [v1.8.0](https://github.com/ilyalesik/react-fetch-hook/releases/tag/v1.8.0).

**Comment by dohomi** [comment]
@ilyalesik Thanks for your quick response and fast fix!
