### ISSUE TITLE
Can't use any other variable names besides 'isLoading' and 'data'?`

### ISSUE THREAD

**Issue by pianoman730** [ilyalesik/react-fetch-hook#4]
Is there a way to make it so I can use multiple useFetch hooks in the same file? Right now I get undefined for either variable that is different than 'isLoading' and 'data'. Is that on purpose?

**Comment by ilyalesik** [comment]
Of course, you can call multiple `useFetch` in the same file/component. For example, you can just assign useFetch result to a variable without object destructuring:
```javascript
const result1 = useFetch(...);
const result2 = useFetch(...);
...
result1.data;
result1.isLoading;
result2.data;
result2.isLoading;
``` 
or you can use object destructuring with passing custom variable names:
```javascript
const {data: data1, isLoading: isLoading1} = useFetch(...);
const {data: data2, isLoading: isLoading2} = useFetch(...);
...
data1;
isLoading1;
data2;
isLoading2;
```

**Comment by ilyalesik** [comment]
I added the [Multiple requests](https://github.com/ilyalesik/react-fetch-hook#multiple-requests) section.
